### ISSUE TITLE
Remove the ip packet from the dependency tree

### ISSUE THREAD

**Issue by masukomi** [datenknoten/ngx-ssb-client#2]
```
ERROR in ./node_modules/ip/lib/ip.js
Module not found: Error: Can't resolve 'os' in '/Users/masukomi/workspace/scuttlebutt/ngx-ssb-client/node_modules/ip/lib'
ℹ ｢wdm｣: Failed to compile.
```

occurred when running `npm run start`  (after running `npm i` ) 

most recent commit is: 

```
commit b9f00926547d5dac9b48ec2a0f743aaf2e6e1bd4
Author: Tim Schumacher <tim@datenknoten.me>
Date:   Sun May 6 22:49:35 2018 +0200

    feat: introduce a feedenderror
```

holler if there's more debugging you'd like. I'm not a node dev so not sure what the standard techniques are but can follow geeky instructions.

**Comment by enko** [comment]
Hey @masukomi 

Thanks for reporting, this is actualy not a mac issue, but a more general problem. Somewhere some package requires the `ip` package, which in turn requires a node environment, which is not available on the browser. I have yet to figure out where this happens, but failed to do so.

I will commit a quick fix, which is a temporary work arround. I will leave this ticket open, till I have fixed the core problem.

Love

Tim
